spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payflow_payment?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Vishwa@data123

  kafka:
    bootstrap-servers: localhost:9092

  wallet:
    service:
      url: http://localhost:8082

  kyc:
    service:
      url: http://localhost:8084


file:
  upload-dir: uploads