#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/payflow_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Vishwa@data123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#jwt:
#  secret: payflow-super-secret-jwt-key-2026-payflow
#  expiration: 3600000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: local


jwt:
  secret: ${JWT_SECRET:payflow-super-secret-jwt-key-2026-payflow}
  expiration: ${JWT_EXPIRATION:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

