server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payflow_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Vishwa@data123
