#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      routes:
#
#        - id: auth-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/auth/**
#
#        - id: wallet-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/wallet/**,/api/v1/wallet/v3/api-docs
#
#        - id: payment-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/payment/**,/api/v1/payment/v3/api-docs
#
#        - id: kyc-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/v1/kyc/**,/api/v1/kyc/v3/api-docs
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: Auth Service
#        url: /api/v1/auth/v3/api-docs
#      - name: Wallet Service
#        url: /api/v1/wallet/v3/api-docs
#      - name: Payment Service
#        url: /api/v1/payment/v3/api-docs
#      - name: KYC Service
#        url: /api/v1/kyc/v3/api-docs
#
#  api-docs:
#    enabled: true
#
#jwt:
#  secret: payflow-super-secret-jwt-key-2026-payflow
#
#logging:
#  level:
#    root: INFO
#    com.vishwaTechEdu: DEBUG
#    org.springframework.cloud.gateway: DEBUG



server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**

        - id: wallet-service
          uri: ${WALLET_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/wallet/**,/api/v1/wallet/v3/api-docs

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/payment/**,/api/v1/payment/v3/api-docs

        - id: kyc-service
          uri: ${KYC_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/kyc/**,/api/v1/kyc/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /api/v1/auth/v3/api-docs
      - name: Wallet Service
        url: /api/v1/wallet/v3/api-docs
      - name: Payment Service
        url: /api/v1/payment/v3/api-docs
      - name: KYC Service
        url: /api/v1/kyc/v3/api-docs

  api-docs:
    enabled: true

jwt:
  secret: ${JWT_SECRET:payflow-super-secret-jwt-key-2026-payflow}

logging:
  level:
    root: INFO
    com.vishwaTechEdu: DEBUG
    org.springframework.cloud.gateway: DEBUG
