server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/payflow_kyc?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root


file:
  upload-dir: /app/uploads

