#server:
#  port: 8084
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/payflow_kyc?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Vishwa@data123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#management:
#  tracing:
#    enabled: false
#
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics



spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  upload-dir: ./uploads

#file:
#  upload-dir: ${FILE_UPLOAD_DIR:uploads}


management:
  endpoints:
    web:
      exposure:
        include: health,metrics

  tracing:
    enabled: false
