server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payflow_kyc?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Vishwa@data123

file:
  upload-dir: /Users/thoparamvishwateja/Documents/vishwaTechEduProjects/payFlow-Fintech/uploads

