version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: payflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: payflow-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: payflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: payflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  zipkin:
    image: openzipkin/zipkin
    container_name: payflow-zipkin
    ports:
      - "9411:9411"

  auth-service:
    build: ./auth-service
    container_name: payflow-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: payflow-super-secret-jwt-key-2026-payflow
      JWT_EXPIRATION: 3600000
    depends_on:
      - mysql

  wallet-service:
    build: ./wallet-service
    container_name: payflow-wallet
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - redis
      - kafka

  payment-service:
    build: ./payment-service
    container_name: payflow-payment
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql
      - kafka

  kyc-service:
    build: ./kyc-service
    container_name: payflow-kyc
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql

  notification-service:
    build: ./notification-service
    container_name: payflow-notification
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  api-gateway:
    build: ./api-gateway
    container_name: payflow-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_SERVICE_URL: http://auth-service:8081
      WALLET_SERVICE_URL: http://wallet-service:8082
      PAYMENT_SERVICE_URL: http://payment-service:8083
      KYC_SERVICE_URL: http://kyc-service:8084
      JWT_SECRET: payflow-super-secret-jwt-key-2026-payflow
    depends_on:
      - auth-service
      - wallet-service
      - payment-service
      - kyc-service

volumes:
  mysql_data:






