spring:
  datasource:
    url: jdbc:mysql://mysql:3306/payflow_wallet?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  kafka:
    bootstrap-servers: kafka:9092
