spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payflow_wallet?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Vishwa@data123

  kafka:
    bootstrap-servers: localhost:9092
